server:
  port: 8899
spring:
  profiles:
    active: true
  datasource:
    url: jdbc:mysql://172.27.85.46:3306/saascms?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true

