server:
  port: 8888


spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.27.85.46:3306/security?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

  security:
    user:
      name: test
      password: 123
mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.security.entity