server:
  port: 8222

spring:
  profiles:
    active: dev
  application:
    name: PROVIDER-TWO

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka
  instance:
    hostname: localhost